apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasks
  namespace: argocd
spec:
  destination:
    namespace: hive
    server: https://kubernetes.default.svc
  project: default
  source:
    path: tasks 
    repoURL: https://github.com/MarcoPalomo/tkn-argoCD.git 
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
